// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1nb0PHWYoiAMw91FR7-S5r33Qq862OfY',
    appId: '1:752573625233:web:a984928ef400c91bbe6030',
    messagingSenderId: '752573625233',
    projectId: 'students-rate',
    authDomain: 'students-rate.firebaseapp.com',
    storageBucket: 'students-rate.appspot.com',
    measurementId: 'G-PQT51EH06Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCTjLMtCpI09Hyj1N4cVMHjnPBltxZNCdw",
    appId: "1:752573625233:android:bf427c63b07fa42cbe6030",
    messagingSenderId: "752573625233",
    projectId: 'students-rate',
    storageBucket: 'students-rate.appspot.com',
    iosBundleId: 'com.example.studentslab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkxlbuZutoJsY_BcTE_4zO3jzjYQnAspI',
    appId: '1:752573625233:ios:14ae5e49ebee0b4abe6030',
    messagingSenderId: '752573625233',
    projectId: 'students-rate',
    storageBucket: 'students-rate.appspot.com',
    iosBundleId: 'com.example.studentslab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1nb0PHWYoiAMw91FR7-S5r33Qq862OfY',
    appId: '1:752573625233:web:25460ffb7386ae99be6030',
    messagingSenderId: '752573625233',
    projectId: 'students-rate',
    authDomain: 'students-rate.firebaseapp.com',
    storageBucket: 'students-rate.appspot.com',
    measurementId: 'G-WB52W59TF5',
  );
}
